runtime: java17
instance_class: F1

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud"
  # Replace these values with your actual Cloud SQL details
  INSTANCE_CONNECTION_NAME: "chat-db-447906:us-central1:a"
  DB_USER: "root"
  DB_PASS: "root"
  DB_NAME: "chat-app"

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: java -Xmx512m -jar app.jar